ci: automated release builds (#342)
* add M1 mac arch build and test

* Update .github/workflows/ci.yml

Co-authored-by: Emilio López <2642849+elopez@users.noreply.github.com>

* Update .github/workflows/ci.yml

Co-authored-by: Emilio López <2642849+elopez@users.noreply.github.com>

* ci: automate release creation when pushing a tag

* ci: upgrade actions/setup-{node,go}

* ci: fix Python dependency installation on macOS

  error: externally-managed-environment

  × This environment is externally managed
  ╰─> To install Python packages system-wide, try brew install
      xyz, where xyz is the package you are trying to
      install.

      If you wish to install a non-brew-packaged Python package,
      create a virtual environment using python3 -m venv path/to/venv.
      Then use path/to/venv/bin/python and path/to/venv/bin/pip.

      If you wish to install a non-brew packaged Python application,
      it may be easiest to use pipx install xyz, which will manage a
      virtual environment for you. Make sure you have pipx installed.

  note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

* ci: use `alls-green` to decide success status

`release` can be skipped, but GitHub will then skip `all-checks`.
We need to check that `release` is successful when it runs, but ignore
it when it is skipped.

---------

Co-authored-by: Anish Naik <anish.naik@trailofbits.com>